spring.datasource.url=jdbc:postgresql://localhost:5432/trading-ms
#Default usernam/pswd for local Posgres server
spring.datasource.username=postgres
spring.datasource.password=
#Create the db on startup then drop it on exit
spring.jpa.hibernate.ddl-auto=create-drop
#Show db requests in the console
spring.jpa.show-sql=true
# swagger-ui custom path
#springdoc.swagger-ui.path=/swagger-ui.html